name: "Xfinity Internet Usage"
description: "Get Xfinity Internet Usage Data"
url: "https://github.com/thor0215/hassio-xfinity-usage"
version: "0.0.9"
slug: "xfinity-usage"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
homeassistant_api: true
hassio_api: true
hassio_role: manager
panel_icon: mdi:network
init: false
map:
  - addon_config:rw

options:
  xfinity_username:
  xfinity_password:
  page_timeout: 45
  polling_rate: 900
  loglevel: info

schema:
  xfinity_username: str
  xfinity_password: password
  page_timeout: int(15,)?
  polling_rate: int(30,)?
  loglevel: list(info|debug|debug_support)?
